feat: premining data & fix refresh
pret-labs/pret-ui pull request #32
Opened 2022-10-22 02:56 UTC by keeplearning-near

2022-10-25 01:50 UTC, linguists requested changes

2022-10-25 01:50 UTC, linguists commented on src/components/menu/Aidrdrop/AirdropModal.tsx
> +const UIINCENTIVEDATAPROVIDER_ABI = [
We should probably query data via `@pret/contract-helper` package. 

We need to update the package here: https://github.com/pret-labs/pret-utilities/blob/master/packages/contract-helpers/src/ui-incentive-data-provider/index.ts

2022-10-25 01:50 UTC, linguists commented on src/ui-config/networks.ts
> +    cornIncentivesController: '0xe303206ac6065ae2a53553116da7ddb54fd24776',
This is duplicate with the 2nd `incentiveDataControllers`

2022-10-25 01:50 UTC, linguists commented on src/ui-config/markets/index.ts
>        LENDING_POOL: '0x8ca1db9e43305636e9b4bf8ca1ff8f97579009ad',
`LENDING_POOL` and `WETH_GATEWAY` also need to be updated.

2022-10-28 00:27 UTC, zhubajie8881 commented
test passed

2022-11-01 10:40 UTC, linguists requested changes

2022-11-01 10:40 UTC, linguists commented on src/ui-config/networks.ts
> +    cornIncentivesController: '0xE303206ac6065aE2a53553116da7ddb54fd24776',
Should we add this into `addresses.incentiveControllers`?

2022-11-01 10:40 UTC, linguists commented on src/components/menu/Aidrdrop/AirdropModal.tsx
> +  const [preminingClaimableAmountRaw, setPreminingClaimableAmountRaw] = useState('0');
```suggestion
  const [preMiningClaimableAmountRaw, setPreMiningClaimableAmountRaw] = useState('0');
```

2022-11-01 10:40 UTC, linguists commented on src/components/menu/Aidrdrop/AirdropModal.tsx
> +  const [preminingData, setPreminingData] = useState<{
```suggestion
  const [preMiningData, setPreMiningData] = useState<{
```

2022-11-04 08:28 UTC, linguists commented on src/ui-config/networks.ts
> +      'https://aurora-mainnet.infura.io/v3/eee0ad1bd3c5487585685be6b7f4ef94',
Is this RPC URL necessary?

2022-11-07 01:36 UTC, linguists approved these changes

2022-11-07 01:38 UTC, merged